apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8-argocd
  name: k8-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-argocd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8-argocd
    spec:
      containers:
      - image: ambawatyuvaraj/argocd:13
        name: k8-argocd
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: k8-argocd